name: CI-CD Pipeline

on:
  workflow_run:
    workflows: ["Docker publish to GHCR"]
    types:
      - completed

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
        env:
          TF_VAR_render_api_key: ${{ secrets.RENDER_API_KEY }}