name: lint and test app

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: install dependencies
        run: pip install flake8
      - name: run flake8
        run: flake8 .

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v6
      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: install dependencies
        run: pip install -r requirements.txt

      - name: Start Flask app
        run: |
          python app.py &

      - name: Wait for API
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:5000/; then
              echo "API is ready"
              break
            fi
            sleep 2
          done

      - name: run tests
        run: pytest

  docker-test:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v6

      - name: Build Docker image
        run: docker build -t api-iscod:latest .

      - name: run docker container
        run: docker run -d --name API_ISCOD -p 5000:5000 api-iscod:latest

      - name: Wait for container API
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:5000/; then
              echo "API ready"
              exit 0
            fi
            sleep 2
          done
          exit 1

      - name: check container status
        run: docker ps --filter name=API_ISCOD

      - name: stop and remove container
        run: |
          docker stop API_ISCOD
          docker rm API_ISCOD